blank_issues_enabled: false
contact_links:
  - name: ⚠ Feature request
    url: https://github.com/initflode/.github/blob/master/docs/project-status.md
    about: Sorry, but this project is in maintenance mode and no longer accepts new feature requests.
  - name: 💬 Discord server
    url: https://discord.gg/flode#59
    about: Chat with the project community.
  - name: 📖 Wiki
    url: https://github.com/initflode/intuba/wiki
    about: Find usage guides and frequently asked questions.
  - name: 🗨 Discussions
    url: https://github.com/initflode/intuba/discussions/new
    about: Ask and answer questions.
